### ISSUE TITLE
DefaultInstance vs FirstInstance

### ISSUE THREAD

**Issue by unique-dominik** [zitadel/zitadel-charts#110]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

As a administrator I want to be informed what the difference and impact of the `DefaultInstance` vs `FirstInstance` is.

---

I did now approx 1h of research and another 1h of trying and non-succeeding. What is the difference between `DefaultInstance` vs `FirstInstance`? 😭 

Start of the problem is [this section of the values](https://github.com/zitadel/zitadel/blob/37cf9f5fb2cb32c7559928b150bf611fe42e637f/cmd/defaults.yaml#L404) or here respectively: https://zitadel.com/docs/self-hosting/manage/configure#whats-next.

```yaml
DefaultInstance:
  InstanceName:
  DefaultLanguage: en
  Org:
    Name:
    Human:
     ...
      UserName: zitadel-admin-1
    ...
```

What does that do? I could not make the login on a fresh installation work. I expect that the `DefaultInstance` is also used for the systems own first instance if no `FirstInstance` is given.

```yaml
FirstInstance:
  InstanceName:
  DefaultLanguage: en
  Org:
    Name:
    Human:
     ...
      UserName: zitadel-adm1n
    ...
```

What is now done? Who wins? What is the impact?

Another thing that I observe is that e.g. `DefaultInstance.InstanceName` does not even work 😢

I see I am not the only one:
- [A](https://github.com/zitadel/zitadel/issues/4452)
- [B](https://github.com/zitadel/zitadel-charts/issues/67#issuecomment-1423778738)
    + here @eliobischof wrote the correct title but did not explain the difference

Could you either point me to the right docs (and I order the glasses) or provide them here or as docs? ❤️ 

Thank you 🏰 

### Additional Context

Discord username: `m4mbax`

The question could also be asked in the official `zitadel` repo, please feel free to suggest a move or move it.

[FirstInstance Reference Link](https://github.com/zitadel/zitadel/blob/2c6a2a376c6e66d659e25bca461265e0a125c557/cmd/setup/steps.yaml#L1)

For reference my current chart looks like this (I removed all user customisations for now as it was so confusing).

```yaml
       zitadel:
          # The chart: https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml
          masterkey: {{ .Values.zitadel.mainKey | fetchSecretValue | quote }}
          configmapConfig:
            # All values: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
            ExternalDomain: {{ .Values.zitadel.hostName }} # ! Changing this breaks the system
            ExternalPort: 443 # ! Changing this breaks the system
            ExternalSecure: true # ! Changing this breaks the system
            LogStore:
              Access:
                Stdout:
                  Enabled: true
            TLS:
              Enabled: false # Application Gateway from Azure does this
            DefaultInstance:
              InstanceName: {{ .Values.zitadel.defaultInstanceName }}
          secretConfig:
            Database:
              cockroach:
                User:
                  Password: {{ .Values.zitadel.password | fetchSecretValue | quote }}
```
