### ISSUE TITLE
Bug: If dbSslRootCrtSecret and/or dbSslClientCrtSecret are defined in default values, they will always be tried to mount

### ISSUE THREAD

**Issue by samip5** [zitadel/zitadel-charts#113]
The conditionals in https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/templates/initjob.yaml#L136 & https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/templates/initjob.yaml#L141 with current default values https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml#L60L63 results in the initjob always trying to mount those secrets.

This results in unable to install application.

**Comment by jessebot** [comment]
I'm also running into this issue, and it makes it so you can't install zitadel with postgresql unfortunately.

**Comment by samip5** [comment]
> I'm also running into this issue, and it makes it so you can't install zitadel with postgresql unfortunately (using only password and username).

I was able to install it despite these issues, but not a fun user experience.

See here: <https://github.com/samip5/k8s-cluster/blob/24ba742b1d8cafa012528c8e7bcdf580fbb48dce/archive/zitadel/app/helm-release.yaml#L71> & <https://github.com/samip5/k8s-cluster/blob/24ba742b1d8cafa012528c8e7bcdf580fbb48dce/archive/zitadel/app/helm-release.yaml#L73>

**Comment by jessebot** [comment]
that fixed that error for me! Thanks, @samip5 !!

**Comment by jessebot** [comment]
Did you ever end up getting this error in the browser when you go to your zitadel domain?

```logtalk
ID=QUERY-n0wng Message=Instance not found
```

It seems to produce this in the zitadel pod's container logs:

<details>
  <summary>click here for logs</summary>
  
```logtalk
time="2023-08-20T09:50:59Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:62"
time="2023-08-20T09:50:59Z" level=warning msg="execution logs are currently in beta" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:207"
time="2023-08-20T09:50:59Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=228218892072255517 workers=1
time="2023-08-20T09:50:59Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=228218892072321053 workers=1
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.personal_access_tokens3
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.projects3
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.keys4
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.orgs
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.authn_keys2
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.user_grants3
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.idp_templates5
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.actions3
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.idp_login_policy_links5
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.idps3
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.user_auth_methods4
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.smtp_configs
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.security_policies
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.flow_triggers2
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.label_policies2
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.oidc_settings2
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.org_domains2
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.lockout_policies2
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.org_metadata2
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.instance_members3
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.secret_generators2
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.notification_policies
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.privacy_policies3
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.custom_texts2
time="2023-08-20T09:51:00Z" level=info msg="query failed" aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505)" eventType=system.projections.scheduler.succeeded instanceID=
time="2023-08-20T09:51:00Z" level=warning msg="unable to push first schedule succeeded" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:275" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: duplicate key value violates unique constraint \"previous_sequence_unique\" (SQLSTATE 23505))" projection=projections.org_members3
time="2023-08-20T09:51:00Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:412"
```

</details>

I have a fairly similar values.yaml to you for zitadel when using postgres like:


<details>
  <summary>click here zitadel values.yaml</summary>

```yaml
zitadel:
  # See all defaults here:
  # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
  configmapConfig:
    Database:
      postgres:
        Host: zitadel-postgres
        Port: 5432
        Database: zitadel
        User:
          SSL:
            Mode: disable
        Admin:
          SSL:
            Mode: disable
    TLS:
      Enabled: false

    # specifies if ZITADEL is exposed externally through TLS
    # this must be set to true even if TLS is not enabled on ZITADEL itself
    # but TLS traffic is terminated on a reverse proxy
    # !!! Changing this after initial setup breaks your system !!!
    ExternalSecure: true
    ExternalPort: 443

    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false

    # setup ZITADEL with a service account
    FirstInstance:
      Org:
        Machine:
          Machine:
            # Creates a service account with the name zitadel-admin-sa,
            # which results in a secret 'zitadel-admin-sa' with a key 'zitadel-admin-sa.json'
            Username: zitadel-admin-sa
            Name: Admin
          MachineKey:
            Type: 1
  # these must be set as is until https://github.com/zitadel/zitadel-charts/issues/113 is resolved
  dbSslRootCrtSecret:
  dbSslClientCrtSecret:
  # Reference the name of the secret that contains the masterkey.
  # The key should be named "masterkey".
  masterkeySecretName: "zitadel-core-key"

replicaCount: 1

# Additional environment variables
# see more here: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
env:
  - name: ZITADEL_EXTERNAL_DOMAIN
    value: "**REDACTED**"
  # all of these come from an external secret
  - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
    valueFrom:
      secretKeyRef:
        name: zitadel-db-credentials
        key: username
  - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-db-credentials
        key: password
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: zitadel-db-credentials
        key: adminUser
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: zitadel-db-credentials
        key: adminPassword

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host:  "**REDACTED**"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: zitadel-tls
      hosts:
        -  "**REDACTED**"

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 6

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 6
```

</details>

<details>
  <summary>click here for postgres values.yaml</summary>

I am still using bitnami's helm chart for postgres and am only passing in a few values:
```yaml
fullnameOverride: zitadel-postgres
global:
  postgresql:
    auth:
      username: zitadel
      existingSecret: zitadel-db-credentials
      secretKeys:
        userPasswordKey: password
        adminPasswordKey: adminPassword
volumePermissions:
  enabled: true
primary:
  pgHbaConfiguration: |-
    local all all trust
    host all all 127.0.0.1/32 md5
    host all zitadel 10.0.0.0/8 md5
    host all postgres 10.0.0.0/8 md5
  persistence:
    enabled: true
    # Use an existing Persistent Volume Claim (must be created ahead of time)
    existingClaim: "zitadel-postgres"
```

</details>

The weird thing is that everything *shows* as healthy:
<img width="1269" alt="Screenshot showing the Argo CD web interface for the zitadel app which shows all resources healthy and up" src="https://github.com/zitadel/zitadel-charts/assets/2389292/ceae63d9-7884-424a-a262-2f6f8d9f0de0">

I wonder if this is a weird thing where Argo CD doesn't play nice with the helm hooks. I don't know if this something you see in flux at all. If you didn't encounter this, no problem. Just thought I'd ask since I'm a bit puzzled.

**Comment by samip5** [comment]
> Did you ever end up getting this error in the browser when you go to your zitadel domain?
> 
> ```logtalk
> ID=QUERY-n0wng Message=Instance not found
> ```
> 

Yes, I did get that error and the [official docs](https://zitadel.com/docs/self-hosting/deploy/troubleshooting#instance-not-found) tell you about it.

**Comment by jessebot** [comment]
Weird that I'm still getting it, because I'm specifying:

```
# Additional environment variables
# see more here: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
env:
  - name: ZITADEL_EXTERNAL_DOMAIN
    value: "**REDACTED**"
```

I might be running into this though: https://github.com/zitadel/zitadel/pull/6367

Thanks again for all your help :)
