### ISSUE TITLE
[Feature] Add the possibility to add CA certificates as volumes/config

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel-charts#127]
In some scenarios customers want to configure zitadel to send outbound traffic through a proxy server.

We [already support defining HTTP_PROXY settings](https://zitadel.com/docs/self-hosting/manage/configure#proxy-configuration) but there is no way mounting a CA file

## Acceptance Criteria

- [ ] Users can mount their CA file (this should mount /etc/ssl/certs/)
- [ ] HTTPS_PROXY can use the CA file

**Comment by unique-dominik** [comment]
@fforootd Is it enough to just mount the directory/file if we so not use the proxy? Can we also set the `SSL_CERT_FILE` environment variable to tell Zitadel to use it. Same here btw, if I make it work at the bank, a meaty PR awaits 😂

**Comment by unique-dominik** [comment]
Self-reply 1 for the docs: Yes, it is enough to just mount them like:

```
extraVolumeMounts:
  - name: ca-certs
    mountPath: /etc/ssl/certs/ca-certs.crt
    readOnly: true
    
extraVolumes:
  - name: ca-certs
    secret:
      defaultMode: 420
      secretName: ca-certs
```
