### ISSUE TITLE
Values from dependency chart not being propagated to zitadel

### ISSUE THREAD

**Issue by mrankitsinghal** [zitadel/zitadel-charts#128]
**Environment**

- Parent Chart: my-service version 0.1.0
- Zitadel Chart: version 5.0.0 from the official repo
- Kubernetes: v1.24

**Steps to Reproduce**

- Added Zitadel chart as a dependency in my-Service Chart.yaml
- Trying to set .zitadel.masterkey in my-Service values.yaml
- Getting error on template render that masterkey is required

**Expected Behavior**
The masterkey value should propagate from my-Service to Zitadel and resolve the error.

**Actual Behavior**
The Zitadel chart is not picking up the masterkey value from dependency and fails on render.

**Configuration**
**my-Service/Chart.yaml**

```yaml
dependencies:
- name: zitadel
  version: 5.0.0
  repository: https://charts.zitadel.com
```

my-Service/values.yaml

```yaml
zitadel:
  enabled: true 
  masterkey: <masterkey>
```

**Debug Details**

- Enabled debug logging in Zitadel - no relevant errors observed
- Tried setting other values like replicaCount but issue persists
- Works fine if Zitadel is installed directly

Let me know if any other details are needed to help troubleshoot this further. Looking forward to your insights on resolving this issue. Thanks!

**Comment by mrankitsinghal** [comment]
Any update on this?

**Comment by lusu007** [comment]
Hey @mrankitsinghal,

You forgot to put the name of your Zitadel dependency before the values you want to set.

Your `my-Service/values.yaml` should look like this:

```yaml
zitadel:
  enabled: true 
  zitadel:
    masterkey: <masterkey>
```
