### ISSUE TITLE
User could not be found when used DefaultInstance in the chart

### ISSUE THREAD

**Issue by suchitsancheti** [zitadel/zitadel-charts#156]
I am trying to deploy the Zitadel on k8s using the helm chart and with the configuration as:

```
zitadel:
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: dev.example.com
    ExternalPort: 443
    TLS:
      Enabled: false
    Log:
      Level: info
      Formatter:
        Format: text
    DefaultInstance:
      InstanceName: MyInstance
      DefaultLanguage: en
      Org:
        Name: MyOrg
        Human:
          FirstName: MyOrg
          LastName: Admin
          DisplayName: MyOrg Admin
          UserName: myorg-admin
          Password: <Password>
          PreferredLanguage: en
      MessageTexts:
        - MessageTextType: InitCode
          Language: en
          Title: "MyOrg - User Initialize User"
          PreHeader: Initialize User
          Subject: Initialize User
          Greeting: "Hello {{.DisplayName}},"
          Text: "This user was created. Use the username {{.PreferredLoginName}} to login. Please click the button below to finish the initialization process. (Code {{.Code}}) If you didn't ask for this mail, please ignore it."
          ButtonText: "Finish initialization"
      SMTPConfiguration:
        SMTP:
          Host: <SMTP Host>
          User: <SMTP User>
          Password: <SMTP Password>
        From: "no-reply@MyOrg.com"
        FromName: "MyOrg Email"
        ReplyToAddress: "no-reply@MyOrg.com"
  configSecretName: zitadel-db-config-secret
  configSecretKey: db_config.yaml

ingress:
  enabled: true
  className: kong
  hosts:
    - host: dev.example.com
      paths:
        - path: /
          pathType: Prefix
              
  
```

When I hit the URL `https://dev.example.com/ui/console` and try to login with user `myorg-admin@myorg.dev.example.com`, it gives the following error:

`User could not be found`

<img width="642" alt="Screenshot 2024-01-01 at 6 00 07 PM" src="https://github.com/zitadel/zitadel-charts/assets/7334255/0cbd554f-b488-4594-aba1-0955dcd84d4a">

- Does Zitadel needs the Organisation to be first created before adding a default instance to any custom organisation? If yes, how to create the Organisation during deployment of the zitadel?
- If not, then what is wrong here?

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you help here?

**Comment by dmonad** [comment]
I think you need to use `FirstInstance` instead.

Here are the default values:
https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml

**Comment by hifabienne** [comment]
I will close this issue, as there has not been an answer to the last comment.
Please feel free to reopen if the problem still exists and you can confirm that you tried the FirstInstance

**Comment by aep** [comment]
hm that doesnt work for me.


```yaml
 values:
    zitadel:
      configmapConfig:
        FirstInstance:
          InstanceName: bob
          Org:
            Human:
              Username: 'root'
              Password: 'RootPassword1!'
              PasswordChangeRequired: true
```


would be nice to have a working example
