### ISSUE TITLE
Allow default annotations to be overriden in a clean way

### ISSUE THREAD

**Issue by thomaspetit** [zitadel/zitadel-charts#161]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Following the PR https://github.com/zitadel/zitadel-charts/issues/159 I'd like to re-align the way we can currently override the default annotations set in this chart. The problem in current chart lies in the fact that it forces you to deploy this chart as a standalone.

In Helm we can make an "umbrella" chart that can be applied by Fleet/ArgoCD/Flux. This umbrella chart might contain Zitadel but also a database like cockroach or postgresql.  An example of this `Chart.yaml`:
```
apiVersion: v2
name: zitadel
version: 0.0.1
description: Zitadel Helm chart
dependencies:
  - name: postgresql
    version: 13.2.29
    repository: https://charts.bitnami.com/bitnami
  - name: zitadel
    version: 7.5.0
    repository: https://charts.zitadel.com
```

The problem that will occur here is that if you want to make sure the postgresql is available before anything else is applied (aka Zitadel) you need to apply a pre-sync hook on all postgres chart resources (if it is even supported by that chart).

### Describe your ideal solution

In the ideal solution I would look into a rework of the way annotations are set but this would probably cause a breaking change as discussed with @arnouthoebreckx .

As I would like to already incrementally fix this setup and ensure that Zitadel can easily be deployed the current proposal is to move these annotations:
```
helm.sh/hook: pre-install,pre-upgrade
helm.sh/hook-delete-policy: before-hook-creation
helm.sh/hook-weight: "1"
```
.. to the `values.yaml` as was basically already done for some resources already like the `initJob` [values.yaml#134](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml#L134)

Goal for the initial PR is to make a **non-breaking change** on the chart

### Version

7.5.0

### App version

v2.41.1

### Additional Context

There are workarounds to this problem for those that do want to know it..

Option 1:
Use ArgoCD annotations and add these the `values.yaml` file.  ArgoCD will always chose ArgoCD annotations before Helm annotations. Cfr: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks

Option 2:
Use another templating engine (on top the Zitadel helm chart) to render the resources. Here's an uggly snippet of that:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 13.2.29
    releaseName: db
    namespace: zitadel
    valuesFile: postgresql.yaml
  - name: zitadel
    repo: https://charts.zitadel.com
    version: 7.5.0
    releaseName: zitadel
    namespace: zitadel
    valuesFile: zitadel.yaml

resources:
  - resources/secret-masterkey.yaml
  - resources/secret-postgresql.yaml
  - resources/secretstore.yaml
  - resources/terraform.yaml

patches:
  - target:
      annotationSelector: helm.sh/hook
    patch: |-
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
  - target:
      annotationSelector: helm.sh/hook-delete-policy
    patch: |-
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy
  - target:
      kind: ServiceAccount
      name: zitadel
    patch: |-
      - op: replace
        path: /metadata/annotations/helm.sh~1hook-weight
        value: -3
  - target:
      kind: Job
      name: zitadel-init
    patch: |-
      - op: replace
        path: /metadata/annotations/helm.sh~1hook-weight
        value: 1
  - target:
      kind: Job
      name: zitadel-setup
    patch: |-
      - op: replace
        path: /metadata/annotations/helm.sh~1hook-weight
        value: 2
  - target:
      kind: Deployment
      name: zitadel
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          helm.sh/hook-weight: 3
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: zitadel-test-connection
```
