### ISSUE TITLE
Add Gateway API support

### ISSUE THREAD

**Issue by amalic** [zitadel/zitadel-charts#203]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I would like the chart do add an opton to use [Gateway API](https://gateway-api.sigs.k8s.io/), similar to [Ingress](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml).

### Describe your ideal solution

values.yaml
```
gateway-api:
  enabled: true
  gateway-class: 
  http-route:
    ...
```

### Version

7.14.0

### App version

2.51.2

### Additional Context

I got a cluster running with Envoy Gateway, and would love if the Zitadel chart could support Gateway API in general.

**Comment by eliobischof** [comment]
I see the value of this feature.
But I give it a lower priority than #207, as you can achieve the same result with #207 and more

**Comment by gecube** [comment]
@amalic Hi! Great improvement! But unfortunately, there are many options how to deploy the API Gateway. Are you sure that you want to give here the whole set of options to change? I managed to deploy zitadel with API Gateway with the next manifests:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zitadel-1
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "34-88-17-164.sslip.io"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: zitadel
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /zitadel.admin.v1.AdminService
        - path:
            type: PathPrefix
            value: /admin
        - path:
            type: PathPrefix
            value: /zitadel.auth.v1.AuthService
        - path:
            type: PathPrefix
            value: /auth
        - path:
            type: PathPrefix
            value: /zitadel.management.v1.ManagementService
        - path:
            type: PathPrefix
            value: /management
        - path:
            type: PathPrefix
            value: /zitadel.system.v1.SystemService
        - path:
            type: PathPrefix
            value: /system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zitadel-2
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "34-88-17-164.sslip.io"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: zitadel
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /assets
        - path:
            type: PathPrefix
            value: /ui
        - path:
            type: PathPrefix
            value: /oidc
        - path:
            type: PathPrefix
            value: /saml
        - path:
            type: PathPrefix
            value: /.well-known/openid-configuration
        - path:
            type: PathPrefix
            value: /openapi
        - path:
            type: PathPrefix
            value: /debug
        - path:
            type: PathPrefix
            value: /device
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zitadel-3
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "34-88-17-164.sslip.io"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: zitadel
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /oauth
```
