### ISSUE TITLE
Change to cert authentication for the zitadel client

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel-charts#25]
https://github.com/zitadel/zitadel-charts/blob/c61c96da6aa0d8bcd36c4ca0f21467ac3454cd80/charts/zitadel/templates/secret_zitadel-secrets.yaml#L2

**Comment by DoGab** [comment]
I have tested if the password was necessary, for me it wasn't. See my test below:

Download a secure-client yaml from here: https://github.com/cockroachdb/helm-charts/blob/master/examples/client-secure.yaml.

Edit the yaml and change the following fields:
- `metadata.namespace` to `zitadel`
- `spec.serviceAccountName` to `crdb`
- `spec.volumes[0].project.sources[0].secret.name` to `cockroachdb-root`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  namespace: zitadel
spec:
  serviceAccountName: crdb
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v21.1.11
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs/
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    projected:
        sources:
          - secret:
              name: cockroachdb-root
              items:
                - key: ca.crt
                  path: ca.crt
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
        defaultMode: 256
```

Deploy the secure client.

```bash
kubectl create -f client-secure.yaml
```

Connect into the container.
```bash
kubectl -n zitadel run cockroachdb --rm -it --image=cockroachdb/cockroach --restart=Never -- /bin/bash
```

Adjust the cert permissions.
```
cp -r ./cockroach-certs/ /client-certs
cd /client-certs
chmod 700 client.root.crt
chmod 700 client.root.key
```

Connect to the database.
```
cockroach sql --certs-dir=/client-certs --host=crdb-public
```

List and connect to the zitadel db.
```sql
> \l
> use zitadel;
> \dt
> select * from projections.login_names;
```
