### ISSUE TITLE
Switch from hooks to using initContainers to wait for dependencies, such as databases, to be ready before initialization.

### ISSUE THREAD

**Issue by lknite** [zitadel/zitadel-charts#280]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Per discussion:
https://github.com/zitadel/zitadel-charts/discussions/270#discussioncomment-11365680

Summary:
zitadel currently uses hooks to wait for a database to be ready, but database will not deploy because zitadel is using hooks, creating a chicken/egg scenario when using helm dependencies.

e.g. Chart.yaml:
```
...
dependencies:
- name: cockroachdb
  version: 11.2.1
  #version: 14.0.5
  repository: https://charts.cockroachdb.com/
- name: zitadel
  version: 8.5.0
  repository: https://charts.zitadel.com
```

### Describe your ideal solution

Either the application itself could watch for the ready status of dependencies, or initContainers could be used to wait for ready status.

Example use case:
I use an initContainer with sealed-secrets because I use external-secrets to provide a "common" secret shared among clusters, external-secrets provides the secret but I need sealed-secrets to wait to start until after the secret is created, because sealed-secrets will not notice the secret if its created after the pod is started.

### Version

latest

### Environment

Self-hosted
