### ISSUE TITLE
Version v2.1.1 can't parse the values

### ISSUE THREAD

**Issue by droslean** [zitadel/zitadel-charts#31]
Example values.yaml
```yaml
zitadel:
  configmapConfig:
    Log:
      Level: 'debug'
      Formatter:  
        Format: json
    ExternalSecure: false
    ExternalDomain: localhost
    FirstInstance:
      Org:
        Human:
          Username: 'root'
          Password: 'RootPassword1!'
    TLS:
      Enabled: false
  masterkey: '.....'
  secretConfig:
    Database:
      cockroach:
        User:
          Username: 'zitadel_user'
          Password: '....'      
        Admin:
          Username: 'root'
          Password: '....'
```

Error
`Values.zitadel.secretConfig.Database.User.Password is mandatory for tls enabled cockroach`
