### ISSUE TITLE
make the setupJob backoffLimit configurable

### ISSUE THREAD

**Issue by firstdorsal** [zitadel/zitadel-charts#314]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Right now this is only possible for the initJob but not the setupJob.

### Describe your ideal solution

```yaml
initJob:
    activeDeadlineSeconds: 1800
    backoffLimit: 10
setupJob:
    activeDeadlineSeconds: 1800
    backoffLimit: 10
```

### Version

8.11.3
