### ISSUE TITLE
Add OCI chart registry and cleanup resources upon release deletion

### ISSUE THREAD

**Issue by hmoazzem** [zitadel/zitadel-charts#321]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

This may not be as important, but should be some enhancements. We're building a [Supabase-like nocode backend](https://github.com/edgeflare/edge) particularly for Kubernetes, and it feels a bit odd to use

1. Make the chart available via OCI registry 

```yaml
  auth:
    zitadel:
      release:
        chartURL: registry-1.docker.io/edgeflare/zitadel:8.12.0 # shouldn't look registry-1.docker.io/zitadel/zitadel:8.12.0?
````

2. Add a [values.schema.json](https://github.com/edgeflare/edge/blob/main/hack/zitadel.values.schema.json)

3. Some resources aren't deleted upon chart un-installation. Apparently, below resources need manual deletion

```sh
kubectl delete cm zitadel-config-yaml
kubectl delete secret zitadel-admin-sa
kubectl delete jobs.batch example-zitadel-init example-zitadel-setup
```

Maybe leaving these is intentional?

### Describe your ideal solution

I mostly follow bitnami/charts for patterns, best-practices etc. In any case, if you think it's useful, I can pick some of the tasks too.

### Version

8.12.0

### App version

v2.70.0
