### ISSUE TITLE
[Bug]: nil pointer evaluating interface {}.initContainers when trying to enable debug

### ISSUE THREAD

**Issue by mustela** [zitadel/zitadel-charts#324]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

8.12.0

### App version

v2.71.1

### Describe the problem caused by this bug

Hey all! Im trying to have run zitadel in debug mode in a k3s/argocd fresh environment. 

The reason why is that the setup can’t finish. It gets stuck on “migration already started, will check again in 5 seconds…” until the job dies. The database is created (which confirms that all the DB parameters are correct), but the migration doesn’t run.

The problem is that if I enable debug, I’m getting the following error:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template zitadel --namespace default --kube-version 1.31 --values /tmp/34c55a40-1ca0-4d89-8305-9ba270c8a62f <api versions removed> --include-crds` failed exit status 1: Error: template: zitadel/templates/debug_replicaset.yaml:34:54: executing "zitadel/templates/debug_replicaset.yaml" at <.Values.debug.initContainers>: nil pointer evaluating interface {}.initContainers Use --debug flag to render out invalid YAML
```
I have tried setting initContainers: [] and extraContainers: [] but I'm getting the same result. 
 

### To reproduce

1. Apply the helm chart

### Logs

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template zitadel --namespace default --kube-version 1.31 --values /tmp/34c55a40-1ca0-4d89-8305-9ba270c8a62f <api versions removed> --include-crds` failed exit status 1: Error: template: zitadel/templates/debug_replicaset.yaml:34:54: executing "zitadel/templates/debug_replicaset.yaml" at <.Values.debug.initContainers>: nil pointer evaluating interface {}.initContainers Use --debug flag to render out invalid YAML
```

### Expected behavior

A debug pod is created so I can inspect zitadel configs and run commands.

### Relevant Configuration

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd  # Ensure ArgoCD is installed in this namespace
spec:
  project: default
  source:
    repoURL: https://charts.zitadel.com
    targetRevision: "8.12.0"
    chart: zitadel
    helm:
      values: |
        image:
          tag: v2.71.1
        zitadel:
          masterkeySecretName: zitadel-masterkey
          debug:
            enabled: true
        env:
          - name: ZITADEL_DATABASE_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: host
          - name: ZITADEL_DATABASE_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: port
          - name: ZITADEL_DATABASE_POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: database
          - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: user
          - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: password
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: postgres-password
          - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: human_username
          - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zitadel-db-credentials
                key: human_password
          - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
            value: disable
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
            value: disable
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
