### ISSUE TITLE
[Bug]: Duplicated labels in deployment

### ISSUE THREAD

**Issue by ivanovaleksey** [zitadel/zitadel-charts#341]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

8.13.2

### App version

2.67.2

### Describe the problem caused by this bug

Hey, I am using the chart with skaffold. I am getting the following error when running `skaffold run`
```
Error: UPGRADE FAILED: error while running post render on files: error while running command /Users/aleksei/Code/google-cloud-sdk/bin/skaffold. error output:
reading Kubernetes YAML: yaml: unmarshal errors:
  line 12: mapping key "app.kubernetes.io/name" already defined at line 8
  line 13: mapping key "app.kubernetes.io/instance" already defined at line 9
  line 34: mapping key "app.kubernetes.io/name" already defined at line 30
  line 35: mapping key "app.kubernetes.io/instance" already defined at line 31
: exit status 1
```

There seems to be an issue with duplicated labels in generated deployment.yaml file
```
# Source: zitadel/charts/zitadel/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
  labels:
    helm.sh/chart: zitadel-8.13.2
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/version: "v2.67.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/component: start
....
```

### To reproduce

Create skaffold file and try to run it
```
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: zitadel
build:
  tagPolicy:
    sha256: { }
deploy:
  helm:
    releases:
      - name: zitadel
        chartPath: ./zitadel
        valuesFiles:
          - ./zitadel/values.test.yaml
        namespace: zitadel
        createNamespace: true

profiles:
  - name: test
    build:
      googleCloudBuild:
        projectId: <...>
    deploy:
      kubeContext: <...>
```
