### ISSUE TITLE
[Bug]: Jobs are timed out when using cloud-sql-proxy

### ISSUE THREAD

**Issue by ivanovaleksey** [zitadel/zitadel-charts#344]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

8.13.3

### App version

v3.2.1

### Describe the problem caused by this bug

Hey, I am having an issue with installing this Helm chart and using a Cloud SQL database.  
I have set up an extra container with `cloud-sql-proxy`, basically just uncommented the section that was there.

The problem is that extra container keeps working after the init script in the main container has finished so the whole job is considered to be running. After this `{{ .Values.initJob.activeDeadlineSeconds }}` amount of time the job is being killed and failed. The installation process doesn't go any further

### To reproduce

1. Specify `extraContainers` with some process that is running infinitely
2. Run `helm install`
3. Either Init (if it's enabled) or setup job will fail because of `activeDeadlineSeconds`

### Logs

```
helm install ...
W0527 19:17:17.768216   36883 warnings.go:70] autopilot-default-resources-mutator:Autopilot updated Job auth/zitadel-init: defaulted unspecified 'cpu' resource for containers [cloud-sql-proxy, zitadel-init] (see http://g.co/gke/autopilot-defaults).
Error: INSTALLATION FAILED: failed pre-install: 1 error occurred:
	* timed out waiting for the condition
```

### Expected behavior

Jobs are able to finish gracefully

### Relevant Configuration

```
  extraContainers:
    # Example; You wish to deploy a cloud-sql-proxy sidecar to all deployments:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
      command:
        - /cloud-sql-proxy
      args:
        - <....>
        - --port=5432
        - --auto-iam-authn
        - --health-check
        - "--http-address=0.0.0.0"
      ports:
        - containerPort: 5432
      startupProbe:
        httpGet:
          path: /startup
          port: 9090
        periodSeconds: 1
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /liveness
          port: 9090
        initialDelaySeconds: 0
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 5
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      lifecycle:
        postStart:
          exec:
            command: ["/cloud-sql-proxy", "wait"]
```
