### ISSUE TITLE
Default USER not working

### ISSUE THREAD

**Issue by Berndinox** [zitadel/zitadel-charts#352]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

Hy,
i did the postgres secure example for kubernetes.
i just added a custom domain.
Issue is non of the default users seems to work: “user non existing”

EDIT Default USER not working...

### Additional Context

```

zitadel:
    masterkey: 123456…

    configmapConfig:
      ExternalSecure: true               
      ExternalDomain: sso.DOMAIN.onl
      TLS:
        Enabled: false                 

      Database:
        Postgres:
          Host: db-postgresql
          Port: 5432
          Database: zitadel
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: zitadel
            SSL:
              Mode: verify-full
          Admin:
            Username: postgres
            SSL:
              Mode: verify-full

    secretConfig:
      Database:
        Postgres:
          User:
            Password: xyz
          Admin:
            Password: abc

    dbSslCaCrtSecret: postgres-cert
    dbSslAdminCrtSecret: postgres-cert
    dbSslUserCrtSecret: zitadel-cert

    # kein interner TLS
    serverSslCrtSecret: “”
    selfSignedCert:
      enabled: false

  env:
    - name: ZITADEL_TLS_MODE
      value: disabled

```

i access via https://ssso.DOMAIN.onl

zitadel-admin@zitadel.localhost
zitadel-admin@localhost
zitadel-admin
zitadel-admin@sso.klaus.onl
zitadel-admin@zitadel.127.0.0.1.sslip.io

i also tried querying the pg db but could not find any….

i ready through this: https://github.com/zitadel/zitadel-charts/issues/110
and added an first instance:

```
      FirstInstance:
        Org:
          Name: admin
          Human:
            Username: ‘admin’
            Password: ‘mypw’
```
admin@sso.DOMAIN.onl
admin@admin.sso.DOMAIN.onl

non are working… :(
