### ISSUE TITLE
Cannot fresh install : zitadel init is in crashloopbackoff

### ISSUE THREAD

**Issue by zifeo** [zitadel/zitadel-charts#57]
Container chown outputs: `chown: /chowned-secrets/*: No such file or directory`

```
zitadel:
  # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
  configmapConfig:
    ExternalPort: 443
    ExternalDomain: ${local.domain}
    ExternalSecure: true
    TLS:
      Enabled: false
    Database:
      postgres:
        Host: postgres-postgresql
        Port: 5432
        Database: zitadel
        User:
          Username: zitadel
          Password: "${random_password.zitadelPassword.result}"
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          Password: "${random_password.postgresPassword.result}"
          SSL:
            Mode: disable
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    Metrics:
      Type: none
  secretConfig: {}
  masterkey: "${random_password.masterkey.result}"
  dbSslRootCrtSecret: null
  dbSslClientCrtSecret: null
```

<img width="632" alt="image" src="https://user-images.githubusercontent.com/9053709/208805761-386af9a3-88d2-4933-b395-3cc725430239.png">
