### ISSUE TITLE
The requested redirect_uri is missing in the client configuration

### ISSUE THREAD

**Issue by fvillain** [zitadel/zitadel-charts#59]
When installing Zitadel from the helm chart with the following configuration :

```yaml
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: id.vhome.fr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: id-domain-fr-tls
          hosts:
            - id.domain.fr
    replicaCount: 1
    zitadel:
      masterkey: "****"
      dbSslRootCrtSecret: "crdb-ca-secret"

      secretConfig:
        Database:
          cockroach:
            User:
              Password: "*****"
      configmapConfig:
        FirstInstance:
          Org:
            Name: domain

        ExternalDomain: id.domain.fr
        ExternalSecure: true
        WebAuthNName: VDOMAIN-IDENTITY
        TLS:
          Enabled: false
        Machine:
          Identification:
            PrivateIp:
              enabled: false
            Hostname:
              enabled: true
            Webhook:
              enabled: false
```

When i go in my browser to https://id.domain.fr i get the following error message:
```
The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application.
```
It's unclear but i guess i have to finish some part of the installation process... What am I missing ?
