### ISSUE TITLE
Zitadel Helm install - nothing displayed once logged in

### ISSUE THREAD

**Issue by unixdaddy** [zitadel/zitadel-charts#64]
I have installed zitadel using the following steps/configuration in kubernetes

1. create namespace called zitadel `kubectl create ns zitadel`
2. installed cockroach db - `helm install crdb cockroachdb/cockroachdb --namespace zitadel --values ./cockroach-values.yaml`
- cockroach-value.yaml contents 
```
  fullnameOverride: crdb
  statefulset:
    replicas: 2
```

3. Installed zitadel -` helm install --namespace zitadel my-zitadel zitadel/zitadel   --values ./zitadel-values.yaml `
- zitadel-values.yaml contents

```
replicaCount: 3
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: my-domain.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: k8s-ingress
      hosts:
        - my-domain.org
zitadel:
  configmapConfig:
    Log:
      Level: 'info'
    ExternalSecure: true
    ExternalDomain: my-domain.org
    ExternalPort: 443
    TLS:
      Enabled: false
    FirstInstance:
      Org:
        Human:
          Username: 'root'
          Password: 'RootPassword1!'
  masterkey: 'MasterkeyNeedsToHave32Characters'
  secretConfig:
    Database:
      cockroach:
        User:
          Username: 'zitadel_user'
          Password: 'a-zitadel-db-user-password'
```
I have nginx ingress controller setup and i can login in but once logged in and I reset my password i get this - i see this message 

![image](https://user-images.githubusercontent.com/8880529/212373886-2372cbeb-4b71-4420-856c-79525dfe1666.png)

then it just spins forever nothing appears
![image](https://user-images.githubusercontent.com/8880529/212373192-33f861c3-3a2d-4260-a2c6-a1bc0455dfae.png)

Not sure what to check.

**Comment by unixdaddy** [comment]
It might be I am missing grpc annotations on ingress. I will try on Monday

**Comment by fforootd** [comment]
> It might be I am missing grpc annotations on ingress. I will try on Monday

Yes this totally sounds like that.

Checkout this piece here https://github.com/zitadel/zitadel/issues/4455#issuecomment-1258460382 that should work

**Comment by unixdaddy** [comment]
@fforootd  that works - thank you for your help

```
#All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
replicaCount: 3
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC" # ADDED THIS LINE
    nginx.ingress.kubernetes.io/configuration-snippet: | # ADDED THIS LINE
      grpc_set_header Host $host;  # ADDED THIS LINE
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: my-domain.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: k8s-ingress
      hosts:
        - my-domain.org
zitadel:
  configmapConfig:
    Log:
      Level: 'info'
    # Make ZITADEL accessible over HTTP, not HTTPS
    ExternalSecure: true
    ExternalDomain: my-domain.org
    ExternalPort: 443
    TLS:
      Enabled: false
     FirstInstance:
      Org:
        Human:
          Username: 'root'
          Password: 'RootPassword1!'
  masterkey: 'MasterkeyNeedsToHave32Characters'
  secretConfig:
    Database:
      cockroach:
        User:
          Username: 'zitadel_user'
          Password: 'a-zitadel-db-user-password'
```
and now i have this :smile:

![image](https://user-images.githubusercontent.com/8880529/212666604-39795bd4-ccf7-4e29-891e-c2c0fa990284.png)
