### ISSUE TITLE
configMapConfig docs aren't consistant 

### ISSUE THREAD

**Issue by hobyte** [zitadel/zitadel-charts#67]
while trying to install zitadel with my own values, I notized that the docs for the configMapConfig are different for the tutorial, the values file in this repo and in the config file in the zitadel repo.

My Values:
```
replicaCount: 1
zitadel: 
  masterkey: "cfMe9lPkty3qFWvX49XgHocLzmStGtyE"
  configmapConfig:
    ExternalPort: 443
    ExternalDomain: id.hobyte.de
    ExternalSecure: true
    TLS:
      Enabled: false
    #FirstInstance:
    DefaultInstance:
      DefaultLanguage: de
      Org:
        Name: cloud
        Human:
          UserName: zitadel-admin
          FirstName: ZITADEL
          LastName: Admin
          Email:
            Address: zitadel-admin@hobyte.de
            Verified: true
          PreferredLanguage: de
      LoginPolicy:
        AllowRegister: false
  secretConfig:
    Database:
      cockroach:
        User:
          Password: "a-zitadel-db-user-password"
```
**Two things that confuse me:**

## secretConfig

In the [tutorial](https://zitadel.com/docs/self-hosting/deploy/kubernetes#install-an-insecure-cockroachdb-and-zitadel-release-that-works-with-localhost) values for the secretConfig are set, but not in the [default Values](https://github.com/zitadel/zitadel-charts/blob/4855ec772c6d333d47abebc03cb351b35e16d860/charts/zitadel/values.yaml#L47) and in the [zitadel config file](https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml), they don't exist. Can they be removed or are these values still needed?

## FirstInstance vs. DefaultInstance

As described in in #66, when using the command and the values from the [tutorial](https://zitadel.com/docs/self-hosting/deploy/kubernetes#install-an-insecure-cockroachdb-and-zitadel-release-that-works-with-localhost) installing is possible, but in any other case, it fails with this error: `Error: template: zitadel/templates/setupjob.yaml:82:74: executing "zitadel/templates/setupjob.yaml" at <.Values.zitadel.configmapConfig.FirstInstance.Org>: nil pointer evaluating interface {}.Org` Is it  DefaultInstance or FirstInstance?
